# Generated by Django 4.0.1 on 2022-01-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0007_peliculas_genero'),
        ('usuario', '0003_alter_user_password'),
        ('favoritos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('user', 'Peliculas')},
        ),
    ]
