# Generated by Django 4.0.1 on 2022-01-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_user_password'),
        ('pelicula', '0008_remove_peliculas_genero'),
        ('favoritos', '0002_alter_favorites_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='Peliculas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas_nombre', to='pelicula.peliculas'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nombre', to='usuario.user'),
        ),
    ]
