# Generated by Django 4.0.1 on 2022-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='una contraseña', max_length=50, verbose_name='password'),
            preserve_default=False,
        ),
    ]
