# Generated by Django 4.0.1 on 2022-01-17 23:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('rango', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=100, verbose_name='Director')),
                ('autores', models.CharField(max_length=100, verbose_name='Autores')),
                ('duracion', models.CharField(max_length=100, verbose_name='Duracion')),
                ('imagen', models.FileField(upload_to='peliculas', verbose_name='portada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
