# Generated by Django 4.0.1 on 2022-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0005_alter_peliculas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='autores',
            field=models.CharField(max_length=100, null=True, verbose_name='Autores'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='duracion',
            field=models.CharField(max_length=100, null=True, verbose_name='Duracion'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='imagen',
            field=models.FileField(blank=True, upload_to='peliculas', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='rango',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
