# Generated by Django 4.0.1 on 2022-01-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0006_alter_peliculas_autores_alter_peliculas_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='genero',
            field=models.TextField(null=True, verbose_name='genero'),
        ),
    ]
